name: Test
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # NOTE: the official macOS runner does not support Docker
          # - macos-latest
          # WARN: HEAD request for the manifest fails on windows-latest
          # WARN: docker build command fails to find Dockerfile
          # - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./
        with:
          input: 'test/data/go.json'
          output: 'test/actual/junit.xml'
      - run: diff test/actual/junit.xml test/expected/junit.xml
